/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TakvimRouteImport } from './routes/takvim'
import { Route as TakipRouteImport } from './routes/takip'
import { Route as SimulasyonRouteImport } from './routes/simulasyon'
import { Route as ScreenerRouteImport } from './routes/screener'
import { Route as RaporRouteImport } from './routes/rapor'
import { Route as PortfoyRouteImport } from './routes/portfoy'
import { Route as PiyasaRouteImport } from './routes/piyasa'
import { Route as KarsilastirRouteImport } from './routes/karsilastir'
import { Route as HaberlerRouteImport } from './routes/haberler'
import { Route as GrafikRouteImport } from './routes/grafik'
import { Route as AyarlarRouteImport } from './routes/ayarlar'
import { Route as AnalizRouteImport } from './routes/analiz'
import { Route as AlarmRouteImport } from './routes/alarm'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'

const TakvimRoute = TakvimRouteImport.update({
  id: '/takvim',
  path: '/takvim',
  getParentRoute: () => rootRouteImport,
} as any)
const TakipRoute = TakipRouteImport.update({
  id: '/takip',
  path: '/takip',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulasyonRoute = SimulasyonRouteImport.update({
  id: '/simulasyon',
  path: '/simulasyon',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerRoute = ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const RaporRoute = RaporRouteImport.update({
  id: '/rapor',
  path: '/rapor',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfoyRoute = PortfoyRouteImport.update({
  id: '/portfoy',
  path: '/portfoy',
  getParentRoute: () => rootRouteImport,
} as any)
const PiyasaRoute = PiyasaRouteImport.update({
  id: '/piyasa',
  path: '/piyasa',
  getParentRoute: () => rootRouteImport,
} as any)
const KarsilastirRoute = KarsilastirRouteImport.update({
  id: '/karsilastir',
  path: '/karsilastir',
  getParentRoute: () => rootRouteImport,
} as any)
const HaberlerRoute = HaberlerRouteImport.update({
  id: '/haberler',
  path: '/haberler',
  getParentRoute: () => rootRouteImport,
} as any)
const GrafikRoute = GrafikRouteImport.update({
  id: '/grafik',
  path: '/grafik',
  getParentRoute: () => rootRouteImport,
} as any)
const AyarlarRoute = AyarlarRouteImport.update({
  id: '/ayarlar',
  path: '/ayarlar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalizRoute = AnalizRouteImport.update({
  id: '/analiz',
  path: '/analiz',
  getParentRoute: () => rootRouteImport,
} as any)
const AlarmRoute = AlarmRouteImport.update({
  id: '/alarm',
  path: '/alarm',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/alarm': typeof AlarmRoute
  '/analiz': typeof AnalizRoute
  '/ayarlar': typeof AyarlarRoute
  '/grafik': typeof GrafikRoute
  '/haberler': typeof HaberlerRoute
  '/karsilastir': typeof KarsilastirRoute
  '/piyasa': typeof PiyasaRoute
  '/portfoy': typeof PortfoyRoute
  '/rapor': typeof RaporRoute
  '/screener': typeof ScreenerRoute
  '/simulasyon': typeof SimulasyonRoute
  '/takip': typeof TakipRoute
  '/takvim': typeof TakvimRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/alarm': typeof AlarmRoute
  '/analiz': typeof AnalizRoute
  '/ayarlar': typeof AyarlarRoute
  '/grafik': typeof GrafikRoute
  '/haberler': typeof HaberlerRoute
  '/karsilastir': typeof KarsilastirRoute
  '/piyasa': typeof PiyasaRoute
  '/portfoy': typeof PortfoyRoute
  '/rapor': typeof RaporRoute
  '/screener': typeof ScreenerRoute
  '/simulasyon': typeof SimulasyonRoute
  '/takip': typeof TakipRoute
  '/takvim': typeof TakvimRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/alarm': typeof AlarmRoute
  '/analiz': typeof AnalizRoute
  '/ayarlar': typeof AyarlarRoute
  '/grafik': typeof GrafikRoute
  '/haberler': typeof HaberlerRoute
  '/karsilastir': typeof KarsilastirRoute
  '/piyasa': typeof PiyasaRoute
  '/portfoy': typeof PortfoyRoute
  '/rapor': typeof RaporRoute
  '/screener': typeof ScreenerRoute
  '/simulasyon': typeof SimulasyonRoute
  '/takip': typeof TakipRoute
  '/takvim': typeof TakvimRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/alarm'
    | '/analiz'
    | '/ayarlar'
    | '/grafik'
    | '/haberler'
    | '/karsilastir'
    | '/piyasa'
    | '/portfoy'
    | '/rapor'
    | '/screener'
    | '/simulasyon'
    | '/takip'
    | '/takvim'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/alarm'
    | '/analiz'
    | '/ayarlar'
    | '/grafik'
    | '/haberler'
    | '/karsilastir'
    | '/piyasa'
    | '/portfoy'
    | '/rapor'
    | '/screener'
    | '/simulasyon'
    | '/takip'
    | '/takvim'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/alarm'
    | '/analiz'
    | '/ayarlar'
    | '/grafik'
    | '/haberler'
    | '/karsilastir'
    | '/piyasa'
    | '/portfoy'
    | '/rapor'
    | '/screener'
    | '/simulasyon'
    | '/takip'
    | '/takvim'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AlarmRoute: typeof AlarmRoute
  AnalizRoute: typeof AnalizRoute
  AyarlarRoute: typeof AyarlarRoute
  GrafikRoute: typeof GrafikRoute
  HaberlerRoute: typeof HaberlerRoute
  KarsilastirRoute: typeof KarsilastirRoute
  PiyasaRoute: typeof PiyasaRoute
  PortfoyRoute: typeof PortfoyRoute
  RaporRoute: typeof RaporRoute
  ScreenerRoute: typeof ScreenerRoute
  SimulasyonRoute: typeof SimulasyonRoute
  TakipRoute: typeof TakipRoute
  TakvimRoute: typeof TakvimRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/takvim': {
      id: '/takvim'
      path: '/takvim'
      fullPath: '/takvim'
      preLoaderRoute: typeof TakvimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takip': {
      id: '/takip'
      path: '/takip'
      fullPath: '/takip'
      preLoaderRoute: typeof TakipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulasyon': {
      id: '/simulasyon'
      path: '/simulasyon'
      fullPath: '/simulasyon'
      preLoaderRoute: typeof SimulasyonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapor': {
      id: '/rapor'
      path: '/rapor'
      fullPath: '/rapor'
      preLoaderRoute: typeof RaporRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfoy': {
      id: '/portfoy'
      path: '/portfoy'
      fullPath: '/portfoy'
      preLoaderRoute: typeof PortfoyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piyasa': {
      id: '/piyasa'
      path: '/piyasa'
      fullPath: '/piyasa'
      preLoaderRoute: typeof PiyasaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karsilastir': {
      id: '/karsilastir'
      path: '/karsilastir'
      fullPath: '/karsilastir'
      preLoaderRoute: typeof KarsilastirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haberler': {
      id: '/haberler'
      path: '/haberler'
      fullPath: '/haberler'
      preLoaderRoute: typeof HaberlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grafik': {
      id: '/grafik'
      path: '/grafik'
      fullPath: '/grafik'
      preLoaderRoute: typeof GrafikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayarlar': {
      id: '/ayarlar'
      path: '/ayarlar'
      fullPath: '/ayarlar'
      preLoaderRoute: typeof AyarlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analiz': {
      id: '/analiz'
      path: '/analiz'
      fullPath: '/analiz'
      preLoaderRoute: typeof AnalizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alarm': {
      id: '/alarm'
      path: '/alarm'
      fullPath: '/alarm'
      preLoaderRoute: typeof AlarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AlarmRoute: AlarmRoute,
  AnalizRoute: AnalizRoute,
  AyarlarRoute: AyarlarRoute,
  GrafikRoute: GrafikRoute,
  HaberlerRoute: HaberlerRoute,
  KarsilastirRoute: KarsilastirRoute,
  PiyasaRoute: PiyasaRoute,
  PortfoyRoute: PortfoyRoute,
  RaporRoute: RaporRoute,
  ScreenerRoute: ScreenerRoute,
  SimulasyonRoute: SimulasyonRoute,
  TakipRoute: TakipRoute,
  TakvimRoute: TakvimRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
